<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Cenario200</name>
  <uuid>e4638b8e-0a4c-4e3c-8e4f-4af318e98abd</uuid>
  <locale>pt_BR</locale>
  <definition><![CDATA[se
	ResultadoTabela é "200" 
então
	atribuir à decisão o valor "Reprovado" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
