<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>DefineDesconto</name>
  <uuid>ba3cc44e-2768-44cf-b1f8-a03da66848f4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 
	'FaturasAtrasadas'
then
	set decision to "desconto de 40%" ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
