<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>1be72367-55c0-4691-85ea-20ddfe987101</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Desconto de 25%" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
