<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>1</name>
  <uuid>5a21f32b-c253-4d4f-9525-1e04e312a49b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	ResultadoTabela is "200"
then
	set decision to "Reprovado" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
