<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>2</name>
  <uuid>2b8ec9b9-ff5a-4be4-a653-60c57196afad</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	ResultadoTabela is "400"
then
	set decision to "Reprovado" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
