<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>52781384-eec9-4348-a4af-f8790762cbe9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Aprovado" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
