<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Reprovado, mas é Prime</name>
  <uuid>3453d3b7-77a6-4560-8bc0-c40f4f668484</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Prime 
then
	set decision to "Gerente de renegociação precisa aprovar" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
