<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>24d90d13-e18c-4a81-858b-cf3192272916</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Aprovado" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
