<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Reprovado porem é Prime</name>
  <uuid>6185727c-a05f-4f19-9a8f-40889336c834</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Prime 
then
	set decision to "Gerente de renegociação precisa aprovar" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
